/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSwitcherRouteImport } from './routes/org/switcher'
import { Route as OrgCreateRouteImport } from './routes/org/create'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSwitcherRoute = OrgSwitcherRouteImport.update({
  id: '/org/switcher',
  path: '/org/switcher',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgCreateRoute = OrgCreateRouteImport.update({
  id: '/org/create',
  path: '/org/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/org/$slug/',
  path: '/org/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org/create': typeof OrgCreateRoute
  '/org/switcher': typeof OrgSwitcherRoute
  '/org/$slug': typeof OrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/org/create': typeof OrgCreateRoute
  '/org/switcher': typeof OrgSwitcherRoute
  '/org/$slug': typeof OrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/org/create': typeof OrgCreateRoute
  '/org/switcher': typeof OrgSwitcherRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/org/create' | '/org/switcher' | '/org/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/org/create' | '/org/switcher' | '/org/$slug'
  id: '__root__' | '/' | '/org/create' | '/org/switcher' | '/org/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgCreateRoute: typeof OrgCreateRoute
  OrgSwitcherRoute: typeof OrgSwitcherRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/switcher': {
      id: '/org/switcher'
      path: '/org/switcher'
      fullPath: '/org/switcher'
      preLoaderRoute: typeof OrgSwitcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/create': {
      id: '/org/create'
      path: '/org/create'
      fullPath: '/org/create'
      preLoaderRoute: typeof OrgCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgCreateRoute: OrgCreateRoute,
  OrgSwitcherRoute: OrgSwitcherRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
